theme: jekyll-theme-architect
description: alu0101068855
<<<<<<< HEAD
title: Práctica 6 - Clases e interfaces genéricas. Principios SOLID
=======
title: Práctica 6 - Clases e interfaces genéricas. Principios SOLID
>>>>>>> 9d6d0d7eebd97cdb2a8b62e7ff3ce69952686ffe
